=== codehaus/prophit/prophit/test/data/profile-data.dtd
<!--
Each document represents a call graph with timing and call count information which was 
captured by a profiler.
-->
<!ELEMENT call-graph ( date, source-file, user, measurement+, invocation+ )>
<!ATTLIST call-graph
  fileVersion ( 1 ) #REQUIRED
  sourceProfiler ( dashprof | hprof ) #REQUIRED
  id ID #REQUIRED
>

<!-- 
Date on which the call graph was created 
Date format is YYYY-MM-DD HH:MM:SS with HH in 24-hour time
-->
<!ELEMENT date ( #PCDATA )>
<!-- The original source file which contained the profile data -->
<!ELEMENT source-file ( #PCDATA )>
<!-- The user who generated this call-graph. Can be obtained from the 'user.name' System property -->
<!ELEMENT user ( #PCDATA )>

<!ELEMENT measurement ( stacktrace )>
<!--
exclusiveTime can always be calculated from the inclusiveTime of a function and the inclusiveTime of its
callees. But it is handy to have it here so that the measurement elements can be used to find hot spots
( stack traces with high exclusive time ).
-->
<!ATTLIST measurement 
  id            ID    #REQUIRED
  inclusiveTime CDATA #REQUIRED
  exclusiveTime CDATA #REQUIRED
  numCalls      CDATA #REQUIRED
>

<!ELEMENT stacktrace ( method+ )>

<!ELEMENT method ( #PCDATA )>

<!-- 
The 'invocation' element represents a method invocation in the program. The caller and callee functions are both
represented by 'measurement' elements, each of which stores its respective stack trace and profile measurement data 
(e.g. time, numCalls).

The 'measurement' elements alone can be used to detect 'hot spots' (stack traces with high inclusive or exclusive times).
But the invocation elements are necessary to build the complete call graph because they relate the measurements to each other.
-->
<!ELEMENT invocation EMPTY>
<!-- 
If there is no callFraction, its call fraction is assumed to be 1 (there is only 1 occurance of it)
If there is no parentRCCID, the rccID is the RCC of a root function (e.g. 'main') 
Any measurementID which appears in more than one invocation must have a callFraction. The callFraction indicates
    the fraction of time for the measurement (referred to by the measurementID) which is assigned to this invocation
  The sum of all the callFractions across all the invocations in which a measurementID appears always equals 1
-->
<!ATTLIST invocation
  parentMeasurementID IDREF #IMPLIED
  measurementID       IDREF #REQUIRED
  callFraction        CDATA #IMPLIED
>

=== codehaus/prophit/trunk/prophit/design/profile-example.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE call-graph SYSTEM "profile-data.dtd" >

<!--
This file represents the parsed and solved profile in data/simple.prof (which is in -prof format)
-->
<call-graph>
	<date>2002-12-10 10:39:00</date>
	<source-file>d:/home/kgilpin/orbit/data/simple.prof</source-file>
	<user>kgilpin</user>
	<!-- In a generated call-graph the measurement/@id attributes will be integers -->
	<measurement id="main" time="300" numCalls="1">
		<stacktrace>
			<method>main()</method>
		</stacktrace>
	</measurement>
	<measurement id="main:test" time="180" numCalls="1">
		<stacktrace>
			<method>main()</method>
			<method>test()</method>
		</stacktrace>
	</measurement>
	<measurement id="main:init" time="120" numCalls="1">
		<stacktrace>
			<method>main()</method>
			<method>init()</method>
		</stacktrace>
	</measurement>
	<measurement id="init:DBExec" time="90" numCalls="1">
		<stacktrace>
			<method>init()</method>
			<method>DBExec()</method>
		</stacktrace>
	</measurement>
	<measurement id="test:DBExec" time="120" numCalls="2">
		<stacktrace>
			<method>test()</method>
			<method>DBExec()</method>
		</stacktrace>
	</measurement>
	<measurement id="DBExec:insert" time="30" numCalls="1">
		<stacktrace>
			<method>DBExec()</method>
			<method>insert()</method>
		</stacktrace>
	</measurement>
	<measurement id="DBExec:update" time="60" numCalls="5">
		<stacktrace>
			<method>DBExec()</method>
			<method>update()</method>
		</stacktrace>
	</measurement>
	<measurement id="insert:append" time="100" numCalls="15">
		<stacktrace>
			<method>insert()</method>
			<method>append()</method>
		</stacktrace>
	</measurement>
	<measurement id="update:append" time="200" numCalls="30">
		<stacktrace>
			<method>update()</method>
			<method>append()</method>
		</stacktrace>
	</measurement>
	<invocation measurementID="main" />
	<invocation parentMeasurementID="main" measurementID="main:test" />
	<invocation parentMeasurementID="main" measurementID="main:init" />
	<invocation parentMeasurementID="main:test" measurementID="test:DBExec" />
	<invocation parentMeasurementID="main:init" measurementID="init:DBExec" />
	<!-- 
	These two invocations are invocations are DBExec:insert from 2 different contexts
	Thus the callFraction numbers specify how the measured data for DBExec:insert should be split
	  between the two invocations

	For -prof profiles, the times are split according to the numCalls of the parentMeasurementIDs.
	  In this case, the split is 1/3 and 2/3, because measurement[@id = 'test:DBExec']/@numCalls = 2
	  and measurement[@id = 'test:DBExec']/@numCalls = 1 
	  (this strange syntax is XPath)	
	--> 
	<invocation parentMeasurementID="test:DBExec" measurementID="DBExec:insert" callFraction="0.6666666667" />
	<invocation parentMeasurementID="init:DBExec" measurementID="DBExec:insert" callFraction="0.3333333333" />
	<!-- Likewise for DBExec:update -->
	<invocation parentMeasurementID="test:DBExec" measurementID="DBExec:update" callFraction="0.6666666667" />
	<invocation parentMeasurementID="init:DBExec" measurementID="DBExec:update" callFraction="0.3333333333" />
	<invocation parentMeasurementID="DBExec:insert" measurementID="insert:append" />
	<invocation parentMeasurementID="DBExec:update" measurementID="update:append" />
</call-graph>

=== codehaus/prophit/trunk/prophit/test/data/simple-profile-std.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE call-graph SYSTEM "profile-data.dtd" >

<!--
This file represents the parsed and solved profile in data/simple.prof (which is in -prof format)
-->
<call-graph>
	<date>2002-12-10 10:39:00</date>
	<source-file>d:/home/kgilpin/orbit/data/simple.prof</source-file>
	<user>kgilpin</user>
	<!-- In a generated call-graph the measurement/@id attributes will be integers -->
	<measurement id="1" time="300" numCalls="1">
		<stacktrace>
			<method>main()</method>
		</stacktrace>
	</measurement>
	<measurement id="2" time="180" numCalls="1">
		<stacktrace>
			<method>main()</method>
			<method>test()</method>
		</stacktrace>
	</measurement> 
	<measurement id="3" time="120" numCalls="1">
		<stacktrace>
			<method>main()</method>
			<method>init()</method>
		</stacktrace>
	</measurement>
	<measurement id="4" time="90" numCalls="1">
		<stacktrace>
			<method>init()</method>
			<method>DBExec()</method>
		</stacktrace>
	</measurement>
	<measurement id="5" time="120" numCalls="2">
		<stacktrace>
			<method>test()</method>
			<method>DBExec()</method>
		</stacktrace>
	</measurement>
	<measurement id="6" time="30" numCalls="1">
		<stacktrace>
			<method>DBExec()</method>
			<method>insert()</method>
		</stacktrace>
	</measurement>
	<measurement id="7" time="60" numCalls="5">
		<stacktrace>
			<method>DBExec()</method>
			<method>update()</method>
		</stacktrace>
	</measurement>
	<measurement id="8" time="100" numCalls="15">
		<stacktrace>
			<method>insert()</method>
			<method>append()</method>
		</stacktrace>
	</measurement>
	<measurement id="9" time="200" numCalls="30">
		<stacktrace>
			<method>update()</method>
			<method>append()</method>
		</stacktrace>
	</measurement>
	<invocation measurementID="1" />
	<invocation parentMeasurementID="1" measurementID="2" />
	<invocation parentMeasurementID="1" measurementID="3" />
	<invocation parentMeasurementID="2" measurementID="5" />
	<invocation parentMeasurementID="3" measurementID="4" />
	<!-- 
	These two invocations are invocations are DBExec:insert from 2 different contexts
	Thus the callFraction numbers specify how the measured data for DBExec:insert should be split
	  between the two invocations

	For -prof profiles, the times are split according to the numCalls of the parentMeasurementIDs.
	  In this case, the split is 1/3 and 2/3, because measurement[@id = 'test:DBExec']/@numCalls = 2
	  and measurement[@id = 'test:DBExec']/@numCalls = 1 
	  (this strange syntax is XPath)	
	--> 
	<invocation parentMeasurementID="5" measurementID="6" callFraction="0.6666666667" />
	<invocation parentMeasurementID="4" measurementID="6" callFraction="0.3333333333" />
	<!-- Likewise for DBExec:update -->
	<invocation parentMeasurementID="5" measurementID="7" callFraction="0.6666666667" />
	<invocation parentMeasurementID="4" measurementID="7" callFraction="0.3333333333" />
	<invocation parentMeasurementID="6" measurementID="8" />
	<invocation parentMeasurementID="7" measurementID="9" />
</call-graph>
