=== codehaus/prophit/tags/MARCH12-SITE/prophit/web/site.dtd
<!ELEMENT site ( page* )>

<!ELEMENT page ( name, page* )>
<!ATTLIST page
	file CDATA #REQUIRED
	templated ( true | false ) "true"
  	>

<!ELEMENT name ( #PCDATA )>

=== codehaus/prophit/prophit/web/site-map.xml
<?xml version="1.0"?>

<!DOCTYPE site SYSTEM "site.dtd">

<site>
  <page templated="false" file="index.html">
    <name>prophIt Home</name>
    <page file="doc.html">
      <name>prophIt Documentation</name>
      <page file="cookbook.html">
        <name>Cookbook</name>
      </page>
      <page file="samples.html">
        <name>Samples</name>
        <page file="hello-list-prof-sample.html">
           <name><![CDATA[Hello List <code>java -prof</code> Profile]]></name>
        </page>
        <page file="hello-list-hprof-sample.html">
           <name><![CDATA[Hello List <code>hprof</code> Profile]]></name>
        </page>
        <page file="hsqldb-hprof-sample.html">
           <name><![CDATA[HSQLDB <code>hprof</code> Profile]]></name>
        </page>
      </page>
      <page file="profiler-types.html">
        <name>Profilers</name>
        <page file="dash-prof.html">
           <name><![CDATA[Java <code>-prof</code>]]></name>
        </page>
        <page file="hprof.html">
           <name><![CDATA[<code>hprof</code>]]></name>
        </page>
      </page>
    </page>
  </page>
</site>
